services:

  catgpt_backend:
    build: ./backend
    container_name: catgpt_backend
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8765:8765" # For Gemini API
      - "2700:2700" # For Vosk API
      - "8008:8008" # For FastAPI
    volumes:
      - ./backend/models:/app/models
      - ./recordings:/recordings
    restart: unless-stopped

  catgpt_frontend:
    build: ./frontend
    container_name: catgpt-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - catgpt_backend
      - postgresql

  postgresql:
    image: postgres:13-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catgpt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: